/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jonathanmantello.tictactoe_jm;

import javax.swing.JOptionPane;

/**
 *
 * @author jonat
 */
public class PlayFrame extends javax.swing.JFrame {
    // Fields
    public Game game;
    
    // Constructor
    public PlayFrame() {
        initComponents();
        centerFrame();
        startNewGame();
    }
    
    // Methods
    private void centerFrame() {
        setLocationRelativeTo(null);
    }
    
    private void startNewGame() {
        game = new Game();
        updateDisplay();
    }
    
    public void displayOutcomeAndStartNewGame() {
        JOptionPane.showMessageDialog(null, game.getOutcome());

        startNewGame();
    }
    
    private void mark(int row, int column) {
        game.markBoard(row, column);
        updateDisplay();
        
        if(game.isFinished()) {
            displayOutcomeAndStartNewGame();
        }
    }

    private void updateDisplay() {
        Box[][] gameboard = game.getGameboard();
        btnR0C0.setText(gameboard[0][0].toString());
        btnR0C1.setText(gameboard[0][1].toString());
        btnR0C2.setText(gameboard[0][2].toString());
        btnR1C0.setText(gameboard[1][0].toString());
        btnR1C1.setText(gameboard[1][1].toString());
        btnR1C2.setText(gameboard[1][2].toString());
        btnR2C0.setText(gameboard[2][0].toString());
        btnR2C1.setText(gameboard[2][1].toString());
        btnR2C2.setText(gameboard[2][2].toString());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CenterPanel = new javax.swing.JPanel();
        btnR0C0 = new javax.swing.JButton();
        btnR0C1 = new javax.swing.JButton();
        btnR0C2 = new javax.swing.JButton();
        btnR1C0 = new javax.swing.JButton();
        btnR1C1 = new javax.swing.JButton();
        btnR1C2 = new javax.swing.JButton();
        btnR2C0 = new javax.swing.JButton();
        btnR2C1 = new javax.swing.JButton();
        btnR2C2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tic Tac Toe");
        setMaximumSize(null);
        setMinimumSize(new java.awt.Dimension(400, 400));
        setPreferredSize(new java.awt.Dimension(400, 400));
        setSize(new java.awt.Dimension(400, 400));

        CenterPanel.setLayout(new java.awt.GridLayout(3, 3, 5, 5));

        btnR0C0.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnR0C0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnR0C0ActionPerformed(evt);
            }
        });
        CenterPanel.add(btnR0C0);

        btnR0C1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnR0C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnR0C1ActionPerformed(evt);
            }
        });
        CenterPanel.add(btnR0C1);

        btnR0C2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnR0C2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnR0C2ActionPerformed(evt);
            }
        });
        CenterPanel.add(btnR0C2);

        btnR1C0.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnR1C0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnR1C0ActionPerformed(evt);
            }
        });
        CenterPanel.add(btnR1C0);

        btnR1C1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnR1C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnR1C1ActionPerformed(evt);
            }
        });
        CenterPanel.add(btnR1C1);

        btnR1C2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnR1C2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnR1C2ActionPerformed(evt);
            }
        });
        CenterPanel.add(btnR1C2);

        btnR2C0.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnR2C0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnR2C0ActionPerformed(evt);
            }
        });
        CenterPanel.add(btnR2C0);

        btnR2C1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnR2C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnR2C1ActionPerformed(evt);
            }
        });
        CenterPanel.add(btnR2C1);

        btnR2C2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnR2C2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnR2C2ActionPerformed(evt);
            }
        });
        CenterPanel.add(btnR2C2);

        getContentPane().add(CenterPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnR0C0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnR0C0ActionPerformed
        mark(0, 0);
    }//GEN-LAST:event_btnR0C0ActionPerformed

    private void btnR0C1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnR0C1ActionPerformed
        mark(0, 1);
    }//GEN-LAST:event_btnR0C1ActionPerformed

    private void btnR0C2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnR0C2ActionPerformed
        mark(0, 2);
    }//GEN-LAST:event_btnR0C2ActionPerformed

    private void btnR1C0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnR1C0ActionPerformed
        mark(1, 0);
    }//GEN-LAST:event_btnR1C0ActionPerformed

    private void btnR1C1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnR1C1ActionPerformed
        mark(1, 1);
    }//GEN-LAST:event_btnR1C1ActionPerformed

    private void btnR1C2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnR1C2ActionPerformed
        mark(1, 2);
    }//GEN-LAST:event_btnR1C2ActionPerformed

    private void btnR2C0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnR2C0ActionPerformed
        mark(2, 0);
    }//GEN-LAST:event_btnR2C0ActionPerformed

    private void btnR2C1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnR2C1ActionPerformed
        mark(2, 1);
    }//GEN-LAST:event_btnR2C1ActionPerformed

    private void btnR2C2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnR2C2ActionPerformed
        mark(2, 2);
    }//GEN-LAST:event_btnR2C2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PlayFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CenterPanel;
    private javax.swing.JButton btnR0C0;
    private javax.swing.JButton btnR0C1;
    private javax.swing.JButton btnR0C2;
    private javax.swing.JButton btnR1C0;
    private javax.swing.JButton btnR1C1;
    private javax.swing.JButton btnR1C2;
    private javax.swing.JButton btnR2C0;
    private javax.swing.JButton btnR2C1;
    private javax.swing.JButton btnR2C2;
    // End of variables declaration//GEN-END:variables

    
}
